[commands]
fly = true
broadcast = true
tpa = true
back = true
home = true
warp = true
notice = true
ping = true

[notice]
title = "Notice"
body = "This is a test notice\nqwq"
button = "OK"

[price]
tpa = 0
back = 0
home = 0
warp = 0
