[commands]
fly = true
broadcast = true
tpa = true
back = true
home = true
warp = true
notice = true
ping = true

[notice]
title = "Notice"
body = "This is a test notice\nqwq"
button = "OK"

[price]
tpa = 50
back = 25
home = 10
warp = 25
